# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-UK"
title: "Obscuro"
subtitle: "Ethereum-compatible confidential smart contract L2 network."
description: "Obscuro is an Ethereum-compatible confidential smart contract L2 network."
url: "https://obscu.ro"
name: "Obscuro"
repository: "corda/obscuro.github.io"
twitter_username: 0xScuro
github_username: corda/obscuro
minimal_mistakes_skin: default
search: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-titles-from-headings
  
titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      strip_title: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
